version: "3.8"
services:
  palworld:
    image: steamcmd/steamcmd
    volumes:
    - "./data:/data"
    - "./palworld_run.sh:/root/palworld_run.sh"
    ports:
    - "8221:8221"
    command: bash -c "./palworld_run.sh"