version: "3.8"
services:
  palworld:
    user:
    - "1000:1000"
    image: steamcmd/steamcmd
    volumes:
    - "./data:/data"
    - "./palworld_run.sh:/root/palworld_run.sh"
    ports:
    - "8221:8221"
    command: ./palworld_run.sh